<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.devops</groupId>
    <artifactId>quiz-app</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <!-- ✅ JAVA 21 -->
    <properties>
        <java.version>21</java.version>
        <spring.boot.version>3.2.5</spring.boot.version>
    </properties>

    <!-- ✅ SPRING BOOT PARENT -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
        <relativePath/>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>

    <!-- ✅ JAR NAME FIX -->
    <build>
        <finalName>quiz-app</finalName>
    </build>

</project>
