apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-deployment
  labels:
    app: quiz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz
  template:
    metadata:
      labels:
        app: quiz
    spec:
      containers:
        - name: quiz
          image: harimurari/quiz-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
