apiVersion: apps/v1
kind: Deployment
metadata:
 name: quiz-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: quiz
 template:
  metadata:
   labels:
    app: quiz
  spec:
   containers:
   - name: quiz
     image: quiz-app
     ports:
     - containerPort: 8080